{
  "formatVersion": "1.1",
  "component": {
    "group": "net.minecraftforge",
    "module": "forgeflower",
    "version": "1.5.478.23-structcontext",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "u7ibfvlce5btdm6kr2fm3kcaa4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "forgeflower-1.5.478.23-structcontext.jar",
          "url": "forgeflower-1.5.478.23-structcontext.jar",
          "size": 711085,
          "sha512": "473b0709e2d59d8d25b998d7cb73a8a17d8da3669c7f5d62d7a980dbe338f441c9cbe432d747dd543357a3b0c1ced190487b03c51b2ed77f3a22809031d2ae89",
          "sha256": "2282c92850f07a12bdd124e4d869648602f6f8b14c57397a7c07395c213596ec",
          "sha1": "b0e4925439093af19fc79b8d29ac6ca97fbe434b",
          "md5": "5ef6f46270350e6d145fb70baa6ac561"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "forgeflower-1.5.478.23-structcontext.jar",
          "url": "forgeflower-1.5.478.23-structcontext.jar",
          "size": 711085,
          "sha512": "473b0709e2d59d8d25b998d7cb73a8a17d8da3669c7f5d62d7a980dbe338f441c9cbe432d747dd543357a3b0c1ced190487b03c51b2ed77f3a22809031d2ae89",
          "sha256": "2282c92850f07a12bdd124e4d869648602f6f8b14c57397a7c07395c213596ec",
          "sha1": "b0e4925439093af19fc79b8d29ac6ca97fbe434b",
          "md5": "5ef6f46270350e6d145fb70baa6ac561"
        }
      ]
    }
  ]
}
