{
  "formatVersion": "1.1",
  "component": {
    "group": "net.minecraftforge.gradle",
    "module": "ForgeGradle",
    "version": "4.0.17-fg4_javadoc_inserter",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "fh57rpoigzfjpitwpjswfoqn2u"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ForgeGradle-4.0.17-fg4_javadoc_inserter.jar",
          "url": "ForgeGradle-4.0.17-fg4_javadoc_inserter.jar",
          "size": 384393,
          "sha512": "099711d7316de53e1dc86f076f3751e8899c233098b84f13fd0667c79f43b25fbaf2294212362c84b3bbc0ab1eb44f410d4bd13e3f34bf8662559e79ca34ee46",
          "sha256": "a5e25166cb0555085f1a4540d3859feec60c8ebbe0bd32a04974b306330cab79",
          "sha1": "a10049cdcc9613888e6b50b74f878b3ae8db2849",
          "md5": "595b5a5cd914b082d0b7c19dc204a7b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.jponge",
          "module": "lzma-java",
          "version": {
            "requires": "1.3"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.nothome",
          "module": "javaxdelta",
          "version": {
            "requires": "2.0.1"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.6"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "30.1-jre"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "de.siegmar",
          "module": "fastcsv",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "artifactural",
          "version": {
            "requires": "2.0.3"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.maven",
          "module": "maven-artifact",
          "version": {
            "requires": "3.6.3"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.httpcomponents",
          "module": "httpclient",
          "version": {
            "requires": "4.5.13"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "srgutils",
          "version": {
            "requires": "0.2.13"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ]
        },
        {
          "group": "net.minecraftforge",
          "module": "DiffPatch",
          "version": {
            "requires": "2.0.2"
          },
          "excludes": [
            {
              "group": "org.ow2.asm",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "DiffPatch",
              "type": "jar",
              "extension": "jar",
              "classifier": "all"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ForgeGradle-4.0.17-fg4_javadoc_inserter.jar",
          "url": "ForgeGradle-4.0.17-fg4_javadoc_inserter.jar",
          "size": 384393,
          "sha512": "099711d7316de53e1dc86f076f3751e8899c233098b84f13fd0667c79f43b25fbaf2294212362c84b3bbc0ab1eb44f410d4bd13e3f34bf8662559e79ca34ee46",
          "sha256": "a5e25166cb0555085f1a4540d3859feec60c8ebbe0bd32a04974b306330cab79",
          "sha1": "a10049cdcc9613888e6b50b74f878b3ae8db2849",
          "md5": "595b5a5cd914b082d0b7c19dc204a7b2"
        }
      ]
    }
  ]
}
