{
  "formatVersion": "1.1",
  "component": {
    "group": "net.minecraftforge",
    "module": "forgeflower",
    "version": "0.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "fiv42gry7raf3d46mowseffnwm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "forgeflower-0.2.3.jar",
          "url": "forgeflower-0.2.3.jar",
          "size": 713535,
          "sha512": "fa9ca9c1692190c5c64cefaf425f8a48ab06861c51bedd50fd8232e81102ad1590125234133fd333f3e9d90b412e6d351950905dd80ffa4710001ec7ef741ae4",
          "sha256": "b8744f50ebecb939629411e9cb9f5ab45cbef9931368f33d844c56690bc54722",
          "sha1": "b44abb9eab963cb38c24c572328a977ece4c358d",
          "md5": "8374376d74a121f231c7d2dd17374009"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "forgeflower-0.2.3.jar",
          "url": "forgeflower-0.2.3.jar",
          "size": 713535,
          "sha512": "fa9ca9c1692190c5c64cefaf425f8a48ab06861c51bedd50fd8232e81102ad1590125234133fd333f3e9d90b412e6d351950905dd80ffa4710001ec7ef741ae4",
          "sha256": "b8744f50ebecb939629411e9cb9f5ab45cbef9931368f33d844c56690bc54722",
          "sha1": "b44abb9eab963cb38c24c572328a977ece4c358d",
          "md5": "8374376d74a121f231c7d2dd17374009"
        }
      ]
    }
  ]
}
